//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aula9lp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tabelasEntities : DbContext
    {
        public tabelasEntities()
            : base("name=tabelasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
       // public virtual DbSet<Cidade> Cidade { get; set; }
       // public virtual DbSet<EstadoCivil> EstadoCivil { get; set; }
       // public virtual DbSet<Pessoa> Pessoa { get; set; }
    }
}
